# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-03 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('period', models.CharField(choices=[('0', 'Diário'), ('1', 'Semanal'), ('2', 'Mensal'), ('3', 'Anual')], max_length=1)),
            ],
            options={
                'verbose_name': 'Example',
                'verbose_name_plural': 'Examples',
            },
        ),
    ]
